from typing import Any, Protocol

from .models import (
    BehaviorSearchRequest,
    ComparisonSearchRequest,
    GraphExpandRequest,
    HybridSearchRequest,
    RelationsSearchRequest,
    ResolveRequest,
    SearchFilters,
)


class EmbeddingProvider(Protocol):
    model: str
    dimensions: int

    async def embed(self, text: str) -> list[float]: ...

    async def health(self) -> bool: ...


class LegalGraphRepository(Protocol):
    async def health(self) -> bool: ...
    async def ensure_indexes(self) -> None: ...
    async def schema(self, include_counts: bool = False) -> dict[str, Any]: ...
    async def list_documents(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_document(self, document_id: str, **kwargs: Any) -> dict[str, Any] | None: ...
    async def outline(self, document_id: str, depth: int, include_content: bool) -> dict[str, Any] | None: ...
    async def resolve(self, request: ResolveRequest) -> list[dict[str, Any]]: ...
    async def get_node(self, node_id: str, **kwargs: Any) -> dict[str, Any] | None: ...
    async def context(self, node_id: str, **kwargs: Any) -> dict[str, Any] | None: ...
    async def vector_search(self, embedding: list[float], index: str, filters: SearchFilters, candidate_k: int, min_score: float) -> list[dict[str, Any]]: ...
    async def keyword_search(self, query: str, filters: SearchFilters, candidate_k: int) -> list[dict[str, Any]]: ...
    async def expand(self, request: GraphExpandRequest) -> dict[str, Any]: ...
    async def relations(self, request: RelationsSearchRequest) -> dict[str, Any]: ...
    async def behaviors(self, request: BehaviorSearchRequest, embedding: list[float]) -> dict[str, Any]: ...
    async def comparisons(self, request: ComparisonSearchRequest, embedding: list[float] | None) -> dict[str, Any]: ...
    async def hydrate_hits(self, hits: list[dict[str, Any]], include_ancestors: bool = True) -> list[dict[str, Any]]: ...
